# Mixin File
# URL: # Update RUL: https://github.com/eslco/base/raw/main/config/mihomo/Mixin.yaml

# You can set any mihomo profile's config at here, it will mixin to the profile.
#
# For example:
#
# global-client-fingerprint: chrome # set fingerprint for TLS transport
# experimental: # experimental config
#   quic-go-disable-gso: false # disable quic-go GSO support
#   quic-go-disable-ecn: false # disable quic-go ECN support
#   dialer-ip4p-convert: false # IP4P support
# proxies: # overwrite proxies
#   - name: "PROXY"
#     type: ss
#     server: proxy.example.com
#     port: 443
#     cipher: chacha20-ietf-poly1305
#     password: "password"
# rules: # overwrite rules
#   - DOMAIN,google.com,PROXY
#   - DOMAIN-SUFFIX,google.com,PROXY
#   - DOMAIN-KEYWORD,google,PROXY
#   - DOMAIN-REGEX,^google.*com,PROXY
#   - GEOSITE,google,PROXY
#   - GEOSITE,cn,DIRECT
#   - IP-CIDR,8.8.8.8/32,DIRECT,no-resolve
#   - GEOIP,telegram,DIRECT
#   - GEOIP,cn,DIRECT
#   - Match,PROXY



# DNS Module
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
    # DOH Prefer http/3，true / false，建议设置为 true
  prefer-h3: true
  respect-rules: true
  # enhanced-mode: fake-ip
  enhanced-mode: redir-host
  # fake-ip-range: 28.0.0.1/8
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain"
    - "+.market.xiaomi.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
    - "*.localhost"
    - "*.local"
    - "*.lan"
  # use-system-hosts: true
  use-hosts: true
  hosts:
  localhost:
   - 127.0.0.1
   - ::1

  # 默认 DNS 服务器
  default-nameserver: *tw_dns
  # Proxy 代理 DNS 服务器
  proxy-server-nameserver: *global_dns
  # namesever尽量用运营商提供的DNS
  nameserver: *tw_dns
  # fallback 回退 DNS 服务器
  fallback: *back_dns

DNS_Definition:
   # 锚点引用
  CN_DNS : &cn_dns
   - 120.53.53.53
   - 223.6.6.6
  TW_DNS : &tw_dns
   - 168.95.192.1
   - 168.95.1.1
  Global_dns : &global_dns
   - https://public.dns.iij.jp/dns-query
   - https://1.0.0.2/dns-query
  Fallback_dns : &back_dns
   - 1.0.0.3
   - 1.1.1.3

  nameserver-policy:
    'geosite:private,cn': *cn_dns  # 引用在主配置中定义的锚点
    'geosite:geolocation-!cn': *global_dns # 引用在主配置中定义的锚点

# Nikki Config Mixin 混入配置 已知 Bug : 重复配置 nameserver-policy:字段 将导致 Startup.Yaml 文档语法错误, Router陷入高负载循环 ，宕机状态
# nameserver-policy:
#  'geosite:private,cn': *cn_dns # Mainland (UDP) DNS IP，不建议使用 DoH / DoT
#  'geosite:geolocation-!cn': *global_dns # 非CN，即国外，一般建议 DoH / DoT